import './globals.css'
import {Providers} from "@/app/provider";
import type {ReactNode} from 'react'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: ReactNode}) {
    console.log('THIS IS ROOT')
  return (
    <html lang="en">
      <head />
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
